### PR TITLE
Add WithArrayValidation to the docs

### PR DESCRIPTION
**Pull request by ahmedash95**
adding [WithArrayValidation](https://github.com/SpartnerNL/Laravel-Excel/pull/3641) to the docs

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Hey I somehow completely missed that you added a new concern for that, I'd prefer to use the WithValidation concern, as the new concern doesn't seem to add any benefit. Can you PR that change?

**Comment by ahmedash95** [comment]
Hey @patrickbrouwers, Thanks for your comment. I've also noticed that in order to support validation in `toCollection` too, we can just stick to the `WithValidation` concern only. doing the PR now.

**Comment by patrickbrouwers** [comment]
Thanks! I guess we can update the `## Row Validation without ToModel` section? The full example of validation doesn't seem necessary?

**Comment by ahmedash95** [comment]
Yep. I'm not sure but it seems that `Row Validation without ToModel` seems a good example for not using WithValidation at all. otherwise, WithValidation is now doing the expected behavior. so I think we can just close the PR.

**Pull request closed without merging**
